### ISSUE TITLE
Total entries errors for queries with group by clause

### ISSUE THREAD

**Issue by mtmorra** [mojotech/scrivener_ecto#35]
```
test "can not be used with a group by clause" do
      create_posts()

      page =
        Comment
        |> group_by([c], c.post_id)
        |> Scrivener.Ecto.Repo.paginate

      assert page.total_entries == 1
end

```

This test fails with the following errors:

```
1) test paginate can not be used with a group by clause (Scrivener.Paginator.Ecto.QueryTest)
     test/scrivener/paginator/ecto/query_test.exs:208
     ** (Postgrex.Error) ERROR 42803 (grouping_error): column "c0.id" must appear in the GROUP BY clause or be used in an aggregate function
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_and_cache/7
       (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:68: Ecto.Repo.Queryable.one/4
       (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:38: Scrivener.Paginater.Ecto.Query.total_entries/3
       (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:10: Scrivener.Paginater.Ecto.Query.paginate/2
       test/scrivener/paginator/ecto/query_test.exs:214: (test)
```

The select statement is important in group by clauses, so excluding it causes these issues.  I realize that using Repo.all with the query that is passed in may not be the most performant option, but at least results would be accurate and it would work for all queries.

**Comment by drewolson** [comment]
I think this can be solved with a subquery. I'll take a look.
