### ISSUE TITLE
no match error when using Repo.preload()

### ISSUE THREAD

**Issue by abitdodgy** [mojotech/scrivener_ecto#52]
I'm using scrivner_ecto 1.3, Phoenix 1.3, and Ecto 2.1. 

I can't get `Repo.preload()` to work. Here's an example:

```elixir
def list_account_memberships(query, %Account{} = account) do
  query
  |> Bodyguard.scope(account)
  |> Repo.preload(user: :credential)
  |> Repo.paginate()
end
```

`Bodyguard.scope(account)` filters down to this:

```elixir
def scope(query, account, _params) do
  from q in query, where: [account_id: ^account.id]
end
```

I can get this to work by using an expression to preload the associations. For example:

```elixir
def list_account_memberships(query, %Account{} = account) do
  query
  |> Bodyguard.scope(account)
  |> expression_preload(user: :credential)
  |> Repo.paginate()
end

defp expression_preload(query, opts), do: from q in query, preload: ^opts
```

Using `Repo.preload()` causes the following error:

```
no match of right hand side value: #Ecto.Query<from m in Paper.Accounts.Membership, where: m.account_id == ^1>
```

Any ideas?

**Comment by BenGiese22** [comment]
I'm also getting an error similar to this when using `Repo.preload()`.

I'm using scrivener_ecto 2.0, phoenix 1.4, and Ecto 3.0.

Currently trying to paginate all `Projects` in our `project_controller.ex` file and trying to just utilize the general limit set in `repo.ex`. 

Current index function:
```elixir
def index(conn, params) do
    # projects = Projects.list_projects()
    projects =
      Project
      |> Repo.paginate(params)
      |> Repo.preload([:images])
    render(conn, "index.json", projects: projects.entries)
  end
```

```
[error] #PID<0.682.0> running CreateInstituteWeb.Endpoint (connection #PID<0.681.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /projects
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: %Scrivener.Page{entries: [%CreateInstitute.Projects.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, contact_email: ....................,  page_number: 1, page_size: 3, total_entries: 7, total_pages: 3}
        (create_institute) lib/create_institute_web/controllers/project_controller.ex:15: CreateInstituteWeb.ProjectController.index/2
        (create_institute) lib/create_institute_web/controllers/project_controller.ex:1: CreateInstituteWeb.ProjectController.action/2
        (create_institute) lib/create_institute_web/controllers/project_controller.ex:1: CreateInstituteWeb.ProjectController.phoenix_controller_pipeline/2
        (create_institute) lib/create_institute_web/endpoint.ex:1: CreateInstituteWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (create_institute) lib/create_institute_web/endpoint.ex:1: CreateInstituteWeb.Endpoint.plug_builder_call/2
        (create_institute) lib/plug/debugger.ex:122: CreateInstituteWeb.Endpoint."call (overridable 3)"/2
        (create_institute) lib/create_institute_web/endpoint.ex:1: CreateInstituteWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:34: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /data/proj/msoe/backend/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /data/proj/msoe/backend/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /data/proj/msoe/backend/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Also having this issue steam from the `Repo.preload()` function call. 

Note: `(MatchError) no match of right hand side value: %Scrivener.Page{entries:` is different and starts with  %Scrivener.Page, not #Ecto.Query

**Comment by BenGiese22** [comment]
A team member of mine had gotten Scrivener to work for us. He stated: "Scrivener works if you pass an unexecuted query into it, we were passing full result sets into it".
