### ISSUE TITLE
`:uuid` being passed into Ecto as a type, rather than `Ecto.UUID`

### ISSUE THREAD

**Issue by kbaird** [mojotech/scrivener_ecto#77]
Pagination appears to pass a `:uuid` type into Ecto for an eventual `cast` attempt as per:
```elxiir
[error] #PID<0.1267.0> running OurAppWeb.Endpoint (connection #PID<0.1266.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /api/v1/redacted_resources
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :uuid.cast/1 is undefined (module :uuid is not available)
        :uuid.cast("a72e8643-5f6a-4882-a419-88be227479d2")
        (ecto_sql) lib/ecto/adapters/sql.ex:554: anonymous fn/2 in Ecto.Adapters.SQL.load_embed/2
        (ecto) lib/ecto/type.ex:1159: Ecto.Type.map/4
        (ecto) lib/ecto/type.ex:800: Ecto.Type.process_loaders/3
        (ecto) lib/ecto/repo/queryable.ex:339: Ecto.Repo.Queryable.struct_load!/6
        (ecto) lib/ecto/repo/queryable.ex:201: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/repo/queryable.ex:158: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
        (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:28: Scrivener.Paginater.Ecto.Query.paginate/2
```

See details at https://github.com/elixir-ecto/ecto/pull/3045

I am continuing to investigate with the hopes of providing a PR.

**Comment by kbaird** [comment]
Appears to be internal to Ecto.
